name: Idea / feature request
description: Suggest something that would make Skin Tracker better
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why would it help you?
